### PR TITLE
enabling chef_handler immediately to make it available during compile phase

### PR DESCRIPTION
**Pull request by majormoses**
@BarthV Thanks for the info you gave me on https://github.com/BarthV/chef-hipchat_handler/issues/2#issuecomment-165132623

I went ahead and tested that this works and confirms its working for me.

An execution time test (was already working)

```
$ cat cookbooks/cc-hipchat/recipes/fail_execution.rb 
ruby_block "failure" do
  block do
    raise "FAILURE!"
  end
end
```

A compile time test

```
$ cat cookbooks/cc-hipchat/recipes/fail_compile.rb 
node.somebsattr.split('')
```

### CODE REVIEW

**Comment by majormoses** [comment]
hold off my test only worked once it had converged once successfully....its failing on:

```
- disable Chef::Handler::Hipchat as a exception handler
    ================================================================================
    Error executing action `enable` on resource 'chef_handler[Chef::Handler::Hipchat]'
    ================================================================================

    LoadError
    ---------
    cannot load such file -- /var/chef/handlers/hipchat_handler.rb

```

**Comment by majormoses** [comment]
I think I need to immediately create the handler file let me test

**Comment by majormoses** [comment]
ok that seemed to work. I am going to do a few more tests...

**Comment by majormoses** [comment]
@BarthV ready for review

**Comment by BarthV** [comment]
0.1.8 released

**Pull request merged**
